### ISSUE TITLE
Invalid link when adding action which needs parameters

### ISSUE THREAD

**Issue by foxycode** [contributte/menu-control#27]
```
Invalid link: Missing parameter $id required by App\Presenters\VpsDetailPresenter::actionDefault()
```

See that I turned of menu visibility and I am also not using breadcrumbs in application. Is it bug or is there any way how to handle this? There was `include` statement in earlier version which doesn't work anymore. That's why I added detail as separate item.

Menu definition:
```yaml
menu:
    default:
        templates:
            menu: %appDir%/Components/Menu/menu.latte
        items:
            VPS:
                link: '#'
                items:
                    VPS:
                        action: VpsList:default
                    VPS detail:
                        action: VpsDetail:default
                        visibility:
                            menu: FALSE
```

Presenter:
```php
final class VpsDetailPresenter extends BasePresenter
{
    public function actionDefault(int $id): void
    {
    }
}
```

Menu template:
```smarty
<ul class="nav navbar-nav" n:if="$menu->hasVisibleItemsOnMenu()">
    {foreach $menu->getVisibleItemsOnMenu() as $item}
        {if $item->hasVisibleItemsOnMenu()}
            <li n:class="dropdown, $item->isActive() ? active">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{$item->getRealTitle()} <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li n:foreach="$item->getVisibleItemsOnMenu() as $subitem" n:class="$subitem->isActive() ? active">
                        <a href="{$subitem->getRealLink()}">{$subitem->getRealTitle()}</a>
                    </li>
                </ul>
            </li>
        {else}
            <li n:class="$item->isActive() ? active">
                <a href="{$item->getRealLink()}">{$item->getRealTitle()}</a>
            </li>
        {/if}
    {/foreach}
</ul>
```
